/****************************************************************************************************
 * WVStatus.h
 *
 * Widevine API status (return) codes
 *
 * (c) Copyright 2011 Google, Inc.
 ***************************************************************************************************/

#ifndef __WVSTATUS_H__
#define __WVSTATUS_H__


typedef enum WVStatus {
  WV_Status_Unknown           = 0,  // INTERNAL

  // CA CGI
  WV_Status_CA_OK         = 1,
  WV_Status_CA_AssetNotFound        = 2,
  WV_Status_CA_AssetSaveFailed      = 3,
  WV_Status_CA_AssetDeleteFailed      = 4,
  WV_Status_CA_AssetAlreadyExist      = 5,
  WV_Status_CA_InternalError        = 6,
  WV_Status_CA_OperationNotAllowed      = 7,
  WV_Status_CA_AssetBlocked       = 8,
  WV_Status_CA_OutsideLicenseWindow     = 9,
  WV_Status_CA_OutsideRegion          = 10,
  WV_Status_CA_SignatureMissing     = 11,
  WV_Status_CA_SignatureNotValid      = 12,
  WV_Status_CA_ProviderUnknown      = 13,
  WV_Status_CA_NetworkErr       = 14,
  WV_Status_CA_EntitlementMessageErr      = 15,
  WV_Status_CA_EntitlementDecodeFailed    = 16,
  WV_Status_CA_ClientNetworkingErr      = 17,
  WV_Status_CA_RequestAborted       = 18,
  WV_Status_CA_ClientKeyMissing     = 19,
  WV_Status_CA_RegServerNotResponding     = 20,
  WV_Status_CA_RegServerDown        = 21,
  WV_Status_CA_PortalMissing        = 22,
  WV_Status_CA_PortalUnknown        = 23,
  WV_Status_CA_AssetIdMissing       = 24,
  WV_Status_CA_OwnerMissing       = 25,
  WV_Status_CA_ProviderMissing      = 26,
  WV_Status_CA_NameMissing        = 27,
  WV_Status_CA_InvalidCCI       = 28,
  WV_Status_CA_InvalidDCP       = 29,
  WV_Status_CA_InvalidLicenseWindow     = 30,
  WV_Status_CA_PolicyNotFound       = 31,
  WV_Status_CA_PolicyRejected       = 32,
  WV_Status_CA_PolicyServerNotResponding    = 33,
  WV_Status_CA_ErrorProcessingClientToken   = 34,
  WV_Status_CA_InvalidRegion        = 35,
  WV_Status_CA_InvalidNonce       = 36,
  WV_Status_CA_InvalidHWID        = 37,
  WV_Status_CA_InvalidToken       = 38,
  WV_Status_CA_InvalidAssetId       = 39,
  WV_Status_CA_InvalidName        = 40,
  WV_Status_CA_InvalidDiversity     = 41,
  WV_Status_CA_InvalidKeyId       = 42,
  WV_Status_CA_ModelNotSupported      = 43,
  WV_Status_CA_InvalidKeyboxSystemID      = 44,
  WV_Status_CA_NoDeviceLicenseAvailable   = 45,
  WV_Status_CA_UnknownCode        = 46,
  WV_Status_CA_InvalidAccessCriteria      = 47,
  WV_Status_CA_RegionMissing        = 48,
  WV_Status_CA_KeyVerificationFailed      = 49,
  WV_Status_CA_STBKeyHashFailed     = 50,
  WV_Status_CA_UnableToGetSharedKey     = 51,
  WV_Status_CA_WrongSystemID        = 52,
  WV_Status_CA_RevokedClientVersion     = 53,
  WV_Status_CA_ClientVersionTampered      = 54,
  WV_Status_CA_ClientVersionMissing     = 55,
  WV_Status_CA_AssetProviderAlreadyExist    = 56,
  WV_Status_CA_DiversityMissing     = 57,
  WV_Status_CA_TokenMissing       = 58,
  WV_Status_CA_ClientModelTampered      = 59,
  WV_Status_CA_AssetKeyTooLarge     = 60,
  WV_Status_CA_DecryptFailed        = 61,
  WV_Status_CA_TooManyAssets        = 62,
  WV_Status_CA_MakeNotSupported     = 63,
  WV_Status_CA_PolicyAlreadyExist     = 64,
  WV_Status_CA_InvalidXML       = 65,
  WV_Status_CA_ProviderViolation      = 66,
  WV_Status_CA_PortalVerificationFailed   = 67,
  WV_Status_CA_PortalOverrideNotAllowed   = 68,
  WV_Status_CA_PortalTimeNotSynced      = 69,
  WV_Status_CA_ClientSignatureMissing     = 70,
  WV_Status_CA_ClientSignatureNotValid    = 71,
  WV_Status_CA_AssetNameTooLarge      = 72,
  WV_Status_CA_UsageUrlMissing      = 73,
  WV_Status_CA_AssetIdExceedsLimit      = 74,
  WV_Status_CA_AssetIdInUsedRange     = 75,
  WV_Status_CA_DeviceServerNotResponding    = 76,
  WV_Status_CA_MakeMissing        = 77,
  WV_Status_CA_ModelMissing       = 78,
  WV_Status_CA_DeviceInfoAlreadyExist     = 79,
  WV_Status_CA_DeviceInfoNotFound     = 80,
  WV_Status_CA_InvalidAccess        = 81,
  WV_Status_CA_AccessMissing        = 82,
  WV_Status_CA_InvalidDate        = 83,
  WV_Status_CA_PortalNotSupported     = 84,
  WV_Status_CA_PortalDeniedByDevice     = 85,
  WV_Status_CA_AddDeviceNotAllowed      = 86,
  WV_Status_CA_PortalNotFound       = 87,
  WV_Status_CA_PortalAlreadyExist                     = 88,
  WV_Status_CA_PortalServerNotResponding    = 89,
  WV_Status_CA_PortalFlagsMissing     = 90,
  WV_Status_CA_AssetDeleted                           = 91,
  WV_Status_CA_AssetUpdated                           = 92,
  WV_Status_CA_AssetUpdateFailed                      = 93,
  WV_Status_CA_IPNotAllowedByPolicy                   = 94,
  WV_Status_CA_AckUrlMissing              = 95,
  WV_Status_CA_HeartbeatUrlMissing      = 96,
  WV_Status_CA_SystemIDMissing            = 97,
  WV_Status_CA_PlatformMissing            = 98,
  WV_Status_CA_OwnerUnknown       = 99,
  WV_Status_CA_InvalidBitrate       = 100,
  WV_Status_CA_InvalidSystemID      = 101,
  WV_Status_CA_DeviceKeyNotFound        = 102,
  WV_Status_CA_DeviceKeyServerNotResponding   = 103,
  WV_Status_CA_AssetKeyNotFound                       = 104,
  WV_Status_CA_MediaDigestSignatureMissing    = 105,
  WV_Status_CA_MediaDigestSignatureNotValid   = 106,
  WV_Status_CA_OK_PersistentStoreFieldProvKeybox  = 107,
  WV_Status_CA_Forbid_PersistentStoreFieldProvKeybox  = 108,

  // Status OK (no error)
  WV_Status_OK          = 200,

  // HTTP Result codes
  WV_Status_Bad_Request         = 400,
  WV_Status_Unauthorized        = 401,
  WV_Status_Not_Found         = 404,
  WV_Status_Method_Not_Allowed      = 405,
  WV_Status_Request_Timeout         = 408,
  WV_Status_Unsupported_Media_Type      = 415,
  WV_Status_Requested_Range_Not_Satisfiable     = 416,
  WV_Status_Invalid_Parameter       = 451,
  WV_Status_Session_Not_Found       = 454,
  WV_Status_Method_Not_Valid_In_This_State    = 455,
  WV_Status_Invalid_Range         = 457,
  WV_Status_Unsupported_Transport       = 461,
  WV_Status_Destination_Unreachable       = 462,
  WV_Status_Terminate_Requested       = 463,
  WV_Status_Internal_Server_Error       = 500,
  WV_Status_Not_Implemented         = 501,
  WV_Status_Service_Unavailable       = 503,
  WV_Status_Service_Response_Error      = 504,

  // Range 512 - 768 Reserved for customers.  License-revoking codes
  WV_Status_Min_TP_Error        = 512,
  WV_Status_Max_TP_Error        = 768,

  // Range 769 - 999 Reserved for customers.  Non-license revoking codes
  WV_Status_Min_TP_NoRevoke_Error       = 769,
  WV_Status_Max_TP_NoRevoke_Error       = 999,

  // WidevineMediaKit
  WV_Status_End_Of_Media        = 1000,
  WV_Status_Invalid_Data_Format       = 1001,
  WV_Status_Invalid_Data_Version      = 1002,
  WV_Status_Parse_Error         = 1003,
  WV_Status_Tamper_Detected         = 1004,
  WV_Status_Truncated_Media         = 1005,
  WV_Status_WVMK_Internal_Error       = 1006,
  WV_Status_Entitlement_Error       = 1007,
  WV_Status_Key_Error         = 1008,
  WV_Status_Value_Out_Of_Range      = 1009,
  WV_Status_System_Error        = 1010,
  WV_Status_Invalid_Response        = 1011,
  WV_Status_Unsupported_Transport_Type    = 1012,
  WV_Status_FileSystem_Error        = 1013,
  WV_Status_User_Cancel         = 1014,
  WV_Status_InvalidState        = 1015,
  WV_Status_InvalidPiggybackFile      = 1016,
  WV_Status_Configuration_Error     = 1017,
  WV_Status_Error_NoAdaptiveTracks      = 1018,
  WV_Status_Invalid_Credentials                       = 1019,
  WV_Status_InitializationFailed                      = 1020,
  WV_Status_AlreadyInitialized                        = 1021,
  WV_Status_NotInitialized                            = 1022,
  WV_Status_NoLicenseManagerInstance                  = 1023,
  WV_Status_Invalid_Track                             = 1024,
  WV_Status_Invalid_Timestamp       = 1025,

  WV_Status_Warning_Download_Stalled      = 2000,
  WV_Status_Warning_Need_Key        = 2001,
  WV_Status_Warning_Not_Available       = 2002,
  WV_Status_Checking_Bandwidth      = 2003,
  WV_Status_Error_Download_Stalled      = 2004,
  WV_Status_Error_Need_Key        = 2005,
  WV_Status_Error_Out_Of_Memory       = 2006,
  WV_Status_Uninitialized         = 2007,
  WV_Status_Internal_Error        = 2008,
  WV_Status_Error_Invalid_Chapter       = 2009,
  WV_Status_Heartbeat_Configuration_Error     = 2010,
  WV_Status_Invalid_Keybox        = 2011,
  WV_Status_Warning_CantVerifyIntegrity     = 2012,
  WV_Status_Warning_ContinuityCounterError    = 2014,
  WV_Status_Warning_Emm_Expired       = 2015,

  // PDL
  WV_Status_PDL_Invalid_State       = 3000,
  WV_Status_PDL_Invalid_Path        = 3001,
  WV_Status_PDL_Already_Exists      = 3002,
  WV_Status_PDL_Invalid_Track       = 3003,
  WV_Status_PDL_DownloadIncomplete      = 3004,
  WV_Status_PDL_AlreadyFinalized      = 3005,

  // License Manager
  WV_Status_LicMgr_OutOfMemory      = 4001,
  WV_Status_LicMgr_LicenseAbsent      = 4002,
  WV_Status_LicMgr_LicenseExpired     = 4003,
  WV_Status_LicMgr_LicenseCorrupted     = 4004,
  WV_Status_LicMgr_LicenseOptionalFieldsMissing = 4005,
  WV_Status_LicMgr_OutsideLicenseWindow   = 4006,
  WV_Status_LicMgr_OutsidePurchaseWindow    = 4007,
  WV_Status_LicMgr_OutsideDistributionWindow    = 4008,
  WV_Status_LicMgr_DataStoreCorrupted     = 4009,
  WV_Status_LicMgr_DataStoreReadFailed    = 4010,
  WV_Status_LicMgr_DataStoreWriteFailed   = 4011,
  WV_Status_LicMgr_DataStoreFileDoesNotExist    = 4012,
  WV_Status_LicMgr_ClockTamperDetected    = 4013,
  WV_Status_LicMgr_EMMError       = 4014,
  WV_Status_LicMgr_NoEMMsPresent      = 4015,
  WV_Status_LicMgr_CACGIError       = 4016,
  WV_Status_LicMgr_AssetNotRegistered     = 4017,
  WV_Status_LicMgr_LicenseRevoked     = 4018,
  WV_Status_LicMgr_CACGIStatusError     = 4019,
  WV_Status_LicMgr_ObserversNotFound      = 4020,
  WV_Status_LicMgr_PendingServerNotification    = 4021,
  WV_Status_LicMgr_DuplicateAsset     = 4022,
  WV_Status_LicMgr_PlaybackModeNotAllowed   = 4023,
  WV_Status_LicMgr_LicenseRefreshRequired   = 4024,

  // Asset Registry API
  WV_Status_AR_AssetAlreadyRegistered     = 4100,

  // Media Transformer API
  WV_Status_Transformer_InvalidSession          = 4200,
  WV_Status_Transformer_UnsupportedConfiguration      = 4201,

  // WV gFiber
  // channel updater
  WV_Status_CU_DBConnectionError      = 5000,
  WV_Status_CU_ParsingError       = 5001,
  WV_Status_CU_RetrievalError       = 5002,
  WV_Status_CU_MissingConfig        = 5003,
  WV_Status_CU_GeneralError       = 5004,

  // broadcast encryptor
  WV_Status_BE_SKSConnectionError     = 5100,
  WV_Status_BE_ECMConnectionError     = 5101,
  WV_Status_BE_ECMStatusError       = 5102,
  WV_Status_BE_GeneralError       = 5103,
  WV_Status_BE_HAModeActive       = 5104,
  WV_Status_BE_HAModeStandby        = 5105,

  // SKS
  WV_Status_SKS_DBConnectionError     = 5200,
  WV_Status_SKS_BroadcastEncryptorConnectionError   = 5201,
  WV_Status_SKS_GeneralError        = 5202,

  // ECMGenerator
  WV_Status_ECMG_RegistrationServerConnectionError  = 5300,
  WV_Status_ECMG_ECMError       = 5301,
  WV_Status_ECMG_GeneralError       = 5302

} WVStatus;



#endif // __WVSTATUS_H__
