#!/bin/sh
#####################################################################
ps | grep lb4wk | grep -v grep > /dev/null
if [ $? -eq 0 ]; then
	echo "browser found";
	ps | grep lb4wk | grep -v grep | awk '{print $1}' | while read pid
	do
		echo "====> kill $pid"
		kill -9 $pid
	done
	exit;
	
fi
#####################################################################
 
